import { useState } from 'react';

import Head from 'next/head';
import styles from '@/styles/Home.module.scss';

import Footer from './components/Footer/Footer';
import Banner from './components/Banner/Banner';
import FarmGroups from './components/farmGroups/FarmGroups';
import HeaderFixed from './components/HeaderFixed/HeaderFixed';
import AlphabetSection from './components/AlphabetSection/AlphabetSection';
import NewsBlock from './components/NewsBlock/NewsBlock';
import CategorySection from './components/CategorySection/CategorySection';

export default function Home() {
  const [openBurger, setOpenBurger] = useState(false);

  const handleBurger = () => {
    setOpenBurger(!openBurger);
  };

  const handleCloseBurger = () => {
    setOpenBurger(false);
  };

  return (
    <>
      <Head>
        <title>Proliki Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeaderFixed
          openBurger={openBurger}
          onBurger={handleBurger}
          onClose={handleCloseBurger}
        />
        <Banner />
        <FarmGroups />
        <AlphabetSection />

        <NewsBlock />

        <CategorySection />

        <Footer />
      </main>
    </>
  );
}
