import { useState } from 'react';
import Head from 'next/head';

import HeaderFixed from '../HeaderFixed/HeaderFixed';
import Footer from '../Footer/Footer';

import MainContainer from '@/pages/common/MainContainer/MainContainer';

const Layout = ({ children }) => {
  const [openBurger, setOpenBurger] = useState(false);

  const handleBurger = () => {
    setOpenBurger(!openBurger);
  };

  const handleCloseBurger = () => {
    setOpenBurger(false);
  };

  return (
    <>
      <Head>
        <title>Proliki Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <HeaderFixed
          openBurger={openBurger}
          onBurger={handleBurger}
          onClose={handleCloseBurger}
        />
        {children}
        <Footer />
      </MainContainer>
    </>
  );
};

export default Layout;
